## Массивы Numpy

### Импортируем библиотеки

In [1]:
import numpy as np

### Одномерные массивы

#### Вводим массивы вручную

In [36]:
a = np.array([1, 2, 3, 3])
b = np.array([0, 3, 7, 5])

#### Обращение к элементам массива

In [37]:
a[-1]
a[0]

1

#### Действия с одномерными массивами

In [38]:
2*a - 3*b
a/b
a**2 + 2*b

C:\Users\almet\AppData\Local\Temp\ipykernel_8728\414575070.py:2: RuntimeWarning: divide by zero encountered in divide
  a/b


array([ 1, 10, 23, 19])

In [39]:
np.dot (a,b) # скалярное произведение

42

In [40]:
(np.dot (a,b)/ np.dot (b,b)) * b # проекция вектора a на вектор b

array([0.        , 1.51807229, 3.54216867, 2.53012048])

In [41]:
len(a) # длина массива

4

#### Равномерные массивы arange

In [48]:
np.arange(1, 1.5, 0.01)

array([1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09, 1.1 ,
       1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.2 , 1.21,
       1.22, 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.3 , 1.31, 1.32,
       1.33, 1.34, 1.35, 1.36, 1.37, 1.38, 1.39, 1.4 , 1.41, 1.42, 1.43,
       1.44, 1.45, 1.46, 1.47, 1.48, 1.49])

### Двумерные массивы

#### Вводим массивы вручную

In [51]:
A = np.array([
             [1,2],
             [2,2],
             [3,0]
             ])

B = np.array([
             [0,1],
             [2,5],
             [2,7]
             ])

#### Обращение к элементам массива

In [56]:
A[0]
A[1][1]

2

#### Действия с двумерными массивами

In [65]:
A

array([[1, 2],
       [2, 2],
       [3, 0]])

In [66]:
A.T # транспонирование

array([[1, 2, 3],
       [2, 2, 0]])

In [73]:
np.dot(A, B.T) # Матричное умножение

array([[ 2, 12, 16],
       [ 2, 14, 18],
       [ 0,  6,  6]])

#### Операции shape и reshape

In [80]:
np.shape(A.T)

(2, 3)

In [78]:
D = np.array([
             [1, 2, 3, 4],
             [2, 2, 5, 7],
             [3, 0, 0, 2]
             ])

In [84]:
D.reshape(12,1)

array([[1],
       [2],
       [3],
       [4],
       [2],
       [2],
       [5],
       [7],
       [3],
       [0],
       [0],
       [2]])